Bugfix/FOUR-4950: Field Date picker does not correctly validate the minimum date (For 4.1)
ProcessMaker/vue-form-elements pull request #325
Opened 2022-01-05 20:36 UTC by agustinbusso

## Issue & Reproduction Steps
Reproduction steps
- Create a screen with 2 datepickers (date1 and date2)
- In date2 in Configuration section, add {{date1}} in Minimum Date field.
- Go to preview and select a date in date1
- Date2 will set the minimum date to the selected date - 1

## Solution
Removed timeZone in config. Added formatIfDate function in dateUtils.

## How to Test
- Create a screen with 2 datepickers (date1 and date2)
- In date2 in Configuration section, add {{date1}} in Minimum Date field.
- Go to preview and select a date in date1
- Date2 will set the minimum date to the selected date

**Working video**

https://user-images.githubusercontent.com/90727999/148285428-d2efd318-5ad4-49e7-a1de-4137f84c6202.mov

## Related Tickets & Packages
- [FOUR-4950](https://processmaker.atlassian.net/browse/FOUR-4950)
- [Added e2e tests](https://processmaker.atlassian.net/browse/FOUR-4950)

2022-01-06 17:59 UTC, nolanpro requested changes
@agustinbusso I noticed a problem with the timezone.

- Change the user's timezone to Pacific/Honolulu in /profile/edit
- In screen builder add a date picker and choose a date with the time 13:00 (1pm)
- The preview data shows `2022-01-20T21:00:00.000Z`
- It should be `2022-01-20T23:00:00.000Z` - 23:00 not 21:00

2022-01-07 22:57 UTC, nolanpro approved these changes

2022-01-13 23:43 UTC, ryancooley reviewed
@agustinbusso You say your solution is “Removed timeZone in config. Added formatIfDate function in dateUtils.” However you have a commit reverting the change that added formatIfDate. Why?

2022-01-14 19:18 UTC, ryancooley approved these changes

2022-01-14 19:18 UTC, merged